src/components/Application/Content/Data.tsx
src/components/Table/Table.tsx

Color errors in red

---

src/components/Application/Content/Data.tsx
src/components/Application/Footer/Actions.tsx
src/components/Table/Table.tsx
src/interfaces/error.ts

Show only errors mode

---

src/components/Application/store.ts
src/components/Table/Table.tsx

Ability to select individual cells

---

src/components/Table/Table.tsx
src/interfaces/error.ts

Improve field filtering

---

src/components/Views/Library/VerticalTabs.tsx
src/components/Views/Package/Content/Element.tsx
src/components/Views/Package/Content/PackageImage.tsx
src/global.d.ts

Fixed type error

---

src/components/Application/Layout.tsx
src/components/Application/Welcome.tsx
src/components/Application/store.ts
src/main.ts

- Adds call to action page
- fixes #46

Added call to action

---

package.json
src/components/Views/Library/Fields/DatePicker.tsx
src/components/Views/Library/Fields/InputField.tsx
src/components/Views/Library/Fields/MultilineField.tsx
src/components/Views/Library/Groups/HeadingSearch.tsx
src/components/Views/Library/Image.tsx
src/components/Views/Library/VerticalTabs.tsx
src/components/Views/Package/Content.tsx
src/components/Views/Package/Content/Contributors.tsx
src/components/Views/Package/Content/Element.tsx
src/components/Views/Package/Content/General.tsx
src/components/Views/Package/Content/Help.tsx
src/components/Views/Package/Content/KeywordsEditor/KeywordsInput.tsx
src/components/Views/Package/Content/PackageImage.tsx
src/components/Views/Package/Navigation/PackageNavigation.tsx
src/components/Views/Package/Utils/help.yaml
src/components/Views/Package/store.tsx
src/global.d.ts
webpack.config.js

- Add Dynamic help to metadata field
- Used yaml-loader to load yaml file
- fixes #21

Add dynamic help for metadata fields

---

src/components/Editors/Report/Actions.tsx
src/components/Editors/Report/store.ts
src/components/Editors/Source/Actions.tsx
src/components/Editors/Source/store.ts
src/settings.ts

- Added export actions only.
- Fixes #49

Add actions to report source editors

---

src/components/Application/Welcome.tsx

- Fix vertical scroll in welcome screen
- Fixes #84

Fix scroll in welcome screen

---

src/components/Controllers/Files/Buttons/CreateButton.tsx
src/components/Parts/Buttons/DefaultButton.tsx
src/components/Parts/Buttons/DropdownButton.tsx

- Fix alignment of menu items in dropdown menu
- fixes #90

Fix dropdown alignment

---

src/components/Parts/Trees/FileTree.tsx
src/interfaces/common.ts

- Add additional icons in the file tree.
- fixes #91

Add icons for different file types

---

src/components/Controllers/Files/Content.tsx
src/components/Controllers/Files/store.ts
src/components/Parts/Trees/FileTree.tsx

- User controlled treeview expand feature
- Expand parent folder on folder creation
- fixes #93

Expand folder in new item add

---

src/client.ts
src/components/Controllers/Files/Buttons/CreateButton.tsx
src/components/Controllers/Files/Content.tsx
src/components/Controllers/Files/Dialog.tsx
src/components/Controllers/Files/Dialogs/LinkDialog.tsx
src/components/Controllers/Files/store.ts

Upload link

---

src/components/Parts/Trees/FileTree.tsx
src/helpers.ts
src/interfaces/common.ts
src/interfaces/file.ts

Update filetree to display label based on errorCount
- fixes #135
---

Add label to files

---

src/components/Controllers/Files/Buttons/ManageButton.tsx
src/components/Controllers/Files/store.ts

Download File

---

src/client.ts
src/components/Application/Browser.tsx
src/components/Application/Content.tsx
src/components/Application/store.ts
src/components/Controllers/Files/Buttons/ManageButton.tsx
src/components/Controllers/Files/Dialogs/FolderDialog.tsx
src/components/Controllers/Files/Dialogs/LinkDialog.tsx
src/components/Controllers/Files/Dialogs/NameDialog.tsx
src/components/Controllers/Files/Files.tsx
src/components/Controllers/Files/Layout.tsx
src/components/Controllers/Table/Actions.tsx
src/components/Controllers/Table/Dialog.tsx
src/components/Controllers/Table/Dialogs/ExportDialog.tsx
src/components/Controllers/Table/Layout.tsx
src/components/Controllers/Table/Table.tsx
src/components/Controllers/Table/store.ts
src/components/Parts/ActionButton.tsx
src/components/Parts/ActionButtonContent.tsx
src/settings.ts

81 export button

---

src/client.ts
src/components/Controllers/Table/store.ts

Add save button action

---

src/components/Controllers/Files/Buttons/DeleteButton.tsx

Set focus to delete confirm button

---

src/components/Editors/Chart/Sections/Channel.tsx
src/components/Editors/Chart/help.yaml

187 fix help messages for chart editor

---

src/client.ts
src/components/Controllers/Table/Dialog.tsx
src/components/Controllers/Table/Dialogs/Error.tsx
src/components/Controllers/Table/Editor.tsx
src/components/Controllers/Table/Menu.tsx
src/components/Controllers/Table/store.ts
src/components/Editors/Table/Datagrid.tsx
src/components/Editors/Table/Table.tsx
src/components/Editors/Table/helpers.ts
src/components/Editors/Table/store.ts
src/components/Parts/Bars/Menu.tsx

Implemented errors mode for Table

---

pyproject.toml
src/server/endpoints/file/list.py
src/server/helpers/file.py
src/server/settings.py
test/server/endpoints/file/test_list.py

File list filter

---

src/client/components/Editors/Dialect/help.yaml
src/client/components/Editors/Package/Layout.tsx
src/client/components/Editors/Package/help.yaml
src/client/components/Editors/Package/store.ts
src/client/components/Editors/Resource/Layout.tsx
src/client/components/Editors/Resource/Sections/Checksum.tsx
src/client/components/Editors/Resource/Sections/Resource.tsx
src/client/components/Editors/Resource/help.yaml
src/client/components/Editors/Schema/Sections/Field.tsx
src/client/components/Editors/Schema/Sections/ForeignKey.tsx
src/client/components/Editors/Schema/help.yaml
src/client/components/Parts/Dialogs/Pick.tsx
src/server/endpoints/package/create.py

Fixes for metadata page 

---

.github/workflows/general.yaml
Makefile
build.py
electron-builder.yaml
package.json

Added build/dist to Github Actions

---

portal/content/docs/index.mdx

Plus add the expression "(beta)" whenever mentioning Open Data Editor.

Update concept note links and cover image

---

Makefile
pyproject.toml
server/endpoints/__init__.py

This PR updates the Development Documentation.
- Add a `make help` command to better understand our file and commands
- Reduce Python Development dependencies. Use ruff for lint and format.

Update development documentation

---

client/components/Application/Buttons/Add.tsx

Change wording of Add files menu buttons

---

portal/content/docs/documentation/comparision-to-alternatives.md

Updated the OpenRefine section in the docs, adding a note about Frictionless Data support.
I would be happy to discuss ways we could integrate with OpenRefine. This PR is a draft until then.
See also https://github.com/OpenRefine/OpenRefine/issues/778

OpenRefine integration

---

README.md

Added Contribution Guide link to the readme

---

package.json
portal/content/docs/contributing/development.md

- fixes outdated Node version
---

Use node@20

---

client/components/Application/Dialogs/AddEmptyFolder.tsx

Change wording on Create Folder action

---

client/components/Controllers/Chart/index.tsx
client/components/Controllers/File/index.tsx
client/components/Controllers/Metadata/index.tsx
client/components/Controllers/Table/index.tsx
client/components/Controllers/Text/index.tsx
client/components/Controllers/View/index.tsx

This has been discussed and decided that they are no longer relevant.

Remove unnecessary ThemeProvider calls.

---

client/components/Application/Dialogs/AddRemoteFile.tsx
client/components/Parts/Dialogs/Input.tsx

@pdelboca this PR should fix the issue you mentioned in this comment: https://github.com/okfn/opendataeditor/issues/344#issuecomment-2124846917
---

Move url validation logic inside AddRemoteFile input

---

client/components/Controllers/Chart/Menu.tsx
client/components/Controllers/File/Menu.tsx
client/components/Controllers/Metadata/Menu.tsx
client/components/Controllers/Table/Menu.tsx
client/components/Controllers/Text/Menu.tsx
client/components/Controllers/View/Menu.tsx
client/components/Parts/Bars/Menu.tsx

Remove Editor button from Tabular data menu panel

---

client/components/Editors/Base/List.tsx
client/components/Editors/Base/ListItem.tsx
client/components/Editors/Chart/Sections/Channels/index.tsx
client/components/Editors/Chart/Sections/Layers.tsx
client/components/Editors/Chart/Sections/Transforms/index.tsx
client/components/Editors/Chart/store.ts
client/components/Editors/Package/Sections/Contributors.tsx
client/components/Editors/Package/Sections/Licenses.tsx
client/components/Editors/Package/Sections/Resources.tsx
client/components/Editors/Package/Sections/Sources.tsx
client/components/Editors/Package/store.ts
client/components/Editors/Resource/Sections/Contributors.tsx
client/components/Editors/Resource/Sections/Licenses.tsx
client/components/Editors/Resource/Sections/Sources.tsx
client/components/Editors/Resource/store.ts
client/components/Editors/Schema/Sections/Fields.tsx
client/components/Editors/Schema/Sections/ForeignKeys.tsx
client/components/Editors/Schema/store.ts
client/settings.ts

Do not display Grid View button in metadata panels

---

client/client.ts
client/components/Application/store.ts
client/settings.ts
client/types/record.ts
server/endpoints/file/index.py
server/endpoints/json/patch.py
server/endpoints/project/__spec__/test_sync.py
server/endpoints/project/sync.py
server/endpoints/table/patch.py
server/endpoints/text/patch.py
server/helpers/file.py
server/helpers/record.py
server/models/history.py
server/models/record.py

- fixes #34
- it covers the cases below:
- if a file is added/moved/deleted outside of the app; the app will update the file browser accordingly (10 sec polling)
- if a file is changed outside of the app it will be reflected in the app next time it's opened
---

Project sync

---

client/components/Editors/Base/List.tsx
client/components/Editors/Resource/Sections/Contributors.tsx
client/components/Editors/Resource/Sections/Licenses.tsx
client/components/Editors/Resource/Sections/Sources.tsx
client/components/Editors/Schema/Sections/ForeignKeys.tsx

Remove search box from Metadata Panel

---

client/components/Editors/Table/columns.tsx

Remove context menu and disable row sorting in row number column

---

client/components/Editors/Table/columns.tsx

Replace yellow background in changed cells by gray border

---

client/components/Parts/Trees/File.tsx

Remove file identifiers from file tree menu

---

client/components/Editors/Table/index.tsx

Remove autoresize option from column context menu

---

client/components/Application/Dialogs/AddRemoteFile.tsx

Change error message

---

client/components/Editors/Table/index.tsx

Remove "Columns" option from Column Context Menu

---

client/components/Application/Content.tsx

Remove "or" and "drag and drop" text from empty screen

---

client/components/Application/Dialogs/FileUpload.tsx

- fixes #509
---
If we have components defined statically it works

Fixed focus issue for the text field

---

client/components/Controllers/Table/Menu.tsx
client/components/Parts/Bars/Menu.tsx

Remove errors button from table menu

---

client/components/Parts/Bars/Menu.tsx

Remove tooltips from datagrid menu

---

client/components/Application/Dialogs/OpenLocation.tsx

Hide Open location dialog based on store value

---

client/components/Editors/Table/columns.tsx
client/helpers/report.ts
client/helpers/table.ts
client/store/actions/table.ts
server/endpoints/table/patch.py

Ability to see and remove extra cells

---

client/components/Editors/Schema/Sections/Fields.tsx
client/components/Editors/Schema/help.yaml

Fix enum constraint

---

client/components/Editors/Table/assets/styles.css
client/components/Editors/Table/columns.tsx
client/components/Editors/Table/index.tsx
client/themes.ts

Modify cell editing styles

---

client/components/Parts/Trees/File.tsx

Fixed file menu crashes

---

client/components/Editors/Table/columns.tsx
client/types/error.ts

Implemented errored label tooltips

---

client/components/Application/Content.tsx
client/store/actions/file.ts

Fixed remote file input

---

Makefile
package.json
portal/content/docs/contributing/development.md

@guergana 
Let's try if it works

v1.1.0-rc.2

---

README.md

- fixes #581
---
Preview - https://github.com/okfn/opendataeditor/tree/581/update-readme-1.1

Updated readme to v1.1

---

client/index.html
client/store/actions/app.ts
desktop/index.ts
desktop/menu.ts
desktop/preload/index.ts
desktop/renderer.ts
desktop/window.ts

@guergana 
Please take a look -- I prototyped the bridge for the menu using "Add new File" action as an example

Prototype menu IPC

---

client/components/Editors/Table/columns.tsx
client/helpers/report.ts
package.json

Indicated row errors

---

client/components/Controllers/Text/Editor.tsx
client/components/Controllers/Text/Menu.tsx

Disable preview for text files

---

client/components/Editors/Resource/Sections/Resource.tsx
client/store/actions/table.ts

Dont accept invalid characters in Metadata Resource name

---

client/components/Parts/Trees/File.tsx
desktop/bridge.ts
desktop/preload/index.ts
pyproject.toml

- fixes #616
---
It also syncs the dev server working folder with the dist's one

Fix "Open File Location" function

---

client/components/Application/Layout.tsx
client/components/Parts/Trees/File.tsx

Extend background to covert context menu in file tree

---

client/components/Application/Content.tsx

Attempt to fix upload feature on empty content screen centering

---

client/components/Controllers/Base/Panels/Source.tsx

Set Source panel height to 100%

---

portal/content/docs/documentation/uploading-data.md

Added Google Sheets note to the docs

---

server/endpoints/file/index.py

Fixed header row detection

---

client/components/Parts/Buttons/SimpleButton.tsx
client/components/Parts/Dialogs/TwoButton.tsx

This PR adds a border to the cancel buttons in the two button dialogs.

Add border to cancel button

---

client/components/Application/Browser.tsx
client/components/Application/Layout.tsx
client/components/Application/Sidebar.tsx
client/components/Parts/Trees/File.tsx

Fixed sidebar geometry

---

client/components/Editors/Resource/Sections/Licenses.tsx
server/endpoints/file/__spec__/test_fetch.py

Enable adding multiple licenses

---

ode/panels/metadata.py

- Allows editable values for fields in the Metadata Schema panel.
- Populate combo box with the list of fields in the schema.
- Enable the saving of the schema to the metadata file and populates the schema from the metadata file.

Allow fields to be editable in Metadata Schema panel.

---

ode/main.py

Show welcome screen if selected file is deleted.

---

ode/assets/style.qss

- Fixes #760 
- It was not possible to add the row label in the corner. What was done was to improve the table styles instead.

Improve table styles

---

requirements.txt

Releases Notes:  https://www.qt.io/blog/qt-for-python-release-6.9

Upgrade to latest PySide6 6.9

---

ode/panels/data.py
ode/panels/errors.py

If we have a `Data Integrity error` like `row-count` we only show the message.

Fix Integrety error

---

ode/panels/data.py

818 and 819 - Disable corner button and ToolTips on TableView

---

ode/assets/style.qss
ode/dialogs/upload.py

Changes Upload Dialog styles

---

ode/panels/data.py
ode/panels/metadata.py
requirements.txt

- Start using pandas to save the files as CSV or Excel instead of Frictionless
- Fix error while changing the column type

Replace the way we save the files to start using pandas instead

---

create-dmg.sh

Fixing the MacOS pipeline for creating the package

---

tests/ode/test_frictionless_errors.py
tests/ode/test_metadata.py

Improve test coverage and document unit testing approach

---

.github/workflows/general.yaml
build.py
ode/panels/metadata.py

This PR fixes #875 by creating a new action for building an AppImage file. I tested it in a [github action run](https://github.com/okfn/opendataeditor/actions/runs/14749815628) and it is working as expected.
I also fixed #872:

Build AppImage

---

ode/main.py

Open File In Location opens default location

---

ode/panels/data.py

Increase limit to 1000 to show the +999 msg

---

requirements.txt

Yesterday they release a new minor version: [Changes 6.9.1](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/doc/changelogs/changes-6.9.1)
---

Upgrade PySide6

---

ode/main.py

Disabling the save button while is saving

---

ode/assets/style.qss
ode/panels/data.py
ode/panels/errors.py
ode/shared.py
tests/ode/test_application.py
tests/ode/test_frictionless_errors.py

Changing error background color

---

ode/__init__.py

Bumps the application version.
---

Bump version

---

ode/assets/style.qss
ode/main.py

Fixes #905 
This is a small followup of #939 to setup the suggested code and make the ODE logo focusable as well.
---

905 improve focus ux

---

ode/dialogs/metadata.py
ode/panels/data.py
tests/ode/test_frictionless_errors.py

Migrate metadata error tests

---

ode/panels/data.py

Disable edition of the first row and allow to open the dialog by double clicking it or pressing enter

---

ode/llama.py

- fixes #951 
@pdelboca @romicolman this is written on the LLM feedback branch. It needs to be merged after that one.

Add free prompt for local LLM

---

ode/assets/style.qss
ode/main.py
ode/panels/data.py

928 - Disable save button if no changes are made

---

ode/assets/style.qss

Aligning styles in AI and Column metadata dialog

---

requirements.txt

Updating PySide6 to its latest patch release.
Changelog: https://code.qt.io/cgit/pyside/pyside-setup.git/tree/doc/changelogs/changes-6.9.2
---

Upgrade PySide6 version

---

ode/llama.py

Fixing error when we have an integer as the header

---

ode/dialogs/metadata.py

Increasing the MaxLength in the Metadata Dialog

---

docs/source/contributing/development.md
ode/__init__.py

PR to bump the version number before the next minor release.
---

Release 1.6.1

---

ode/main.py
ode/panels/data.py

Fixing issues while saving different sheets and updating the column's header

---

ode/llama.py

Change default button for AI Dialog and show a warning when a model is not selected

---

ode/llama.py

Changing the multilingual setup in the context to only speak English.

---

ode/assets/style.qss
ode/dialogs/llm_dialog_warning.py
ode/llama.py

1024 second ai use case 

---

docs/source/documentation/ai-integration.md
ode/llama.py

Implementing AI feedback
