okfn/opendataeditor

- package.json
- fixes problems with type errors when using Popper
More about the errors and solution below:
https://github.com/mui/material-ui/issues/35287
---
> update mui/material to latest version 5.11.8

- pyproject.toml
This addresses the hatch issue with specifying the Python version - I get exactly the same error (on Python 3.11) as described here: https://github.com/pypa/hatch/issues/906
The workaround is to remove the Python version from the `pyproject.toml`
> Remove python version from pyproject

- Makefile
- package.json
- pyproject.toml
- fixes tests/CI
- fixes #303 
---
> Recover development flow (tests/CI); remove `lxml` dependency (via `pyquery`)

- desktop/window.ts
Still in the process of getting my virtual box but I am suspecting the problem lies in titleBarStyle property that was set to 'hidden'.
More info: https://www.electronjs.org/docs/latest/tutorial /window-customization#apply-custom-title-bar-styles-macos-windows
- fixes #275 
---
> Show desktop app window frame with default window buttons

- .github/workflows/general.yaml
This PR adds a build workflow and stores the artifacts in Github Actions. 
This can be handy to easily access the distribution files to test. Without the need to pull, build and dist every PR we want to test.
More info: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
1. Go the the Actions sections
2. Click on the Action run by the PR (example: https://github.com/okfn/opendataeditor/actions/runs/8815010899)
3. Navigate to the bottom
4. You should be able to download a `.zip` files with the installers.
> Add build workflow to upload artifacts.

- client/components/Editors/Package/Layout.tsx
- client/components/Parts/Boxes/Scroll.tsx
- client/components/Parts/Grids/Columns.tsx
These modifications are affecting mainly the Chart and PackageData editors.
- fixes #235 
---
> Make editors take 100% of height

- client/components/Editors/Chart/index.tsx
- client/components/Editors/Config/index.tsx
- client/components/Editors/Dialect/index.tsx
- client/components/Editors/Package/index.tsx
- client/components/Editors/Portal/index.tsx
- client/components/Editors/Resource/index.tsx
- client/components/Editors/Schema/index.tsx
- client/components/Editors/View/index.tsx
- client/components/Views/Report/index.tsx
This is a continuation of https://github.com/okfn/opendataeditor/pull/376
Now only one ThemeProvider call remains, and it is at the top of the application component.
> Cleanup unnecessary ThemeProviders

- client/components/Controllers/Table/Editor.tsx
- client/components/Controllers/Table/store.ts
- client/components/Editors/Table/index.tsx
- client/helpers/history.ts
- client/helpers/table.ts
- client/types/history.ts
- server/endpoints/table/patch.py
- server/models/history.py
> Enable multi-cell selection for deleting content of cells

- client/components/Controllers/Table/store.ts
Fixes #391 
This PR is part of understanding and documenting the indexing flow of tabular data.
@roll and @guergana  I'm proposing this idea to start documenting what are the properties and when are they used. I think will improve a lot the readability of the codebase.
I couldn't find any reference nor use of the ` error?: types.IError` property. @roll correct me if I'm wrong.
> 391 document indexing and table store

- client/components/Controllers/Table/Editor.tsx
> Add backspace on key functionality for deleting of multiple cells

- client/components/Editors/Table/index.tsx
> Hide lock/unlock and group/ungroup functions from context menu

- client/components/Editors/Table/index.tsx
- fixes #425 
The issue is fixed here, however, the columns are displayed all the way to the top of the application. I have created [an issue in the reactdatagrid repo](https://github.com/inovua/reactdatagrid/issues/421) to address this topic.
> Change the position of the column context menu to show all columns

- client/components/Application/Buttons/Add.tsx
- fixes #423 
Making use the unused 'complete' prop fixes the issue.
> Close dropdown menu after adding files or folders

- client/components/Application/Dialogs/AddRemoteFile.tsx
- client/store/actions/file.ts
- server/endpoints/file/fetch.py
- fixes #439
---
This PR adds support for Google Sheets, also communicates if the link is invalid or the table is not published. The most time consuming part of this work was looking for possibilities to access the name of the Google Sheet - https://github.com/okfn/opendataeditor/issues/439#issuecomment-2247089316 - and I would say that I don't see any option to do so using anonymous access to Google API directly or via libs (basically the only type of access we can afford within this app architecture).
> Implemented Google Sheets support

- .github/workflows/general.yaml
Currently E2E workflow running on master is failing due to missing Github Token: https://github.com/okfn/opendataeditor/actions/runs/10351212921/job/28649240460
```
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
at new GitHubPublisher (/home/runner/work/opendataeditor/opendataeditor/node_modules/electron-publish/src/gitHubPublisher.ts:52:15)
at createPublisher (/home/runner/work/opendataeditor/opendataeditor/node_modules/app-builder-lib/src/publish/PublishManager.ts:303:14)
at PublishManager.getOrCreatePublisher (/home/runner/work/opendataeditor/opendataeditor/node_modules/app-builder-lib/src/publish/PublishManager.ts:222:19)
at PublishManager.scheduleUpload (/home/runner/work/opendataeditor/opendataeditor/node_modules/app-builder-lib/src …
```
> Fix missing token for E2E Workflow

- test/data/valid.csv
- test/specs/test.e2e.ts
This PR implements a small E2E test case that uploads a CSV and check that it is displayed correctly (File Navigator, Editor and Validation Chip).
I'm writing a lot of verbose comments to document some behaviors of the WebdriverIO library that I'm not sure are happening because I'm not using it correcly, because it is a buggy behaviour, or because there is something smelly in our React components.
I guess that in time we are going to understand WebdriverIO better.
---
> Add a test for a basic CSV file upload

- client/components/Controllers/File/Menu.tsx
- client/components/Controllers/Table/Menu.tsx
- client/components/Controllers/Text/Menu.tsx
Only hiding the button from the menu, not deleting the component because we will again work on this after the pre-release. We only need to hide it temporarily
- fixes #502
> Hide Chat AI button

- client/components/Parts/Trees/File.tsx
- fixes #524 
I'm simplifying the toggle logic. The native one works just fine.
[simplescreenrecorder-2024-08-30_14.19.38.webm](https://github.com/user-attachments/assets/403ec5e7-9c04-4098-98d8-f1cf1d69551a)
---
> Fix issue when toogling folders

- client/components/Application/Browser.tsx
- client/components/Application/Layout.tsx
- client/components/Application/LowerMenu.tsx
- client/components/Application/Sidebar.tsx
This PR fixes a current issue with our layout.
I'm migrating from `flex` (which is designed to let the content guide the layout) to `grid` (which is designed to have a fixed layout).
We are always going to have the same layout, so both `sidebar` and `content` dimensions should **not depend** on it's contents but rather be fixed. Therefore, `grid` makes more sense.
---
> Fix main screen layout issue.

- client/components/Application/Dialogs/FileUpload.tsx
- Fixes #527 
It also adds a `cursor: pointer` to the elements.
---
> 527 remove shortcuts

- client/store/actions/table.ts
This is a tiny step towards making the experience of editing a little bit more intuitive.
Currently, we have this isolated line of code that forces the user input to be converted to an integer if the cell is "number". This causes the famous `NaN` that confused some users.
I'm removing this from the front-end to move towards a more freely experience of editing the data.
---
> 348 do not cast values when editing the Grid

- client/components/Application/Browser.tsx
- client/components/Parts/Trees/File.tsx
- fixes #543 
When are we going to re-enable this @romicolman ? I have added comments because it will be easier for me to re-enable it afterwards. Otherwise I can delete the comments :grimacing:
> Disable multi select

- client/components/Editors/Table/columns.tsx
- client/types/error.ts
- fixes #563 
---
@romicolman 
I don't think we can easily change the situation described in #563 as any save of the file does a few automatic normalizations:
- fill empty labels
- remove extra cells
- etc
This behaviour is implemented in `frictionless-py` and changing it might be quite complicated especially taking into account that these normalizations are done towards fixing tabular errors.
This PR just fixes the missing empty row tooltip.
> Show empty row tooltip

- client/components/Editors/Schema/Sections/Fields.tsx
- client/components/Parts/Fields/Multiselect.tsx
> Fixed field name editing

- client/components/Editors/Schema/Sections/Fields.tsx
- pyproject.toml
- server/helpers/resource.py
- new flag implemented in `fricitonless-py` - https://github.com/frictionlessdata/frictionless-py/pull/1691
- fixes #552 
- fixes #554
- fixes #555
---
Tested constraints:
> Fix Table Schema constraints handling

- .github/workflows/general.yaml
It has been reported that the built version is not running in older versions of Mac. I have created this PR to target version 13 in mac for the generated build in CI to see if this solves the issue.
---------------------------
@roll we have created this PR to address the issue that the app is not installing in mac versions 14+, I have made a build for mac-13 that has been tested in `mac-13` and `mac-14` and installs the app successfully. (Tested by @Faithkenny and @romicolman manually).
The possible explanation can be found on this thread:
```
https://forums.developer.apple.com/forums/thread/739988
Right. macOS 14 introduced a new container data protection feature. To learn more about that, see the link in Trusted Execution Resources.The solution here is to sign your code with a stable …
```
> Make build in CI for Mac 13, not for latest

- client/client.ts
- client/components/Controllers/Table/Editor.tsx
- client/components/Editors/Base/List.tsx
- client/components/Editors/Base/ListItem.tsx
- client/components/Editors/Schema/Sections/Fields.tsx
- client/components/Editors/Table/columns.tsx
- client/components/Editors/Table/index.tsx
- client/components/Parts/Dialogs/Input.tsx
- client/store/actions/table.ts
- server/endpoints/column/__init__.py
- server/endpoints/column/rename.py
- fixes #571 
- fixes #574
---
After deep investigation the conclusion was that it's basically impossible to keep all the editing functionality at the same time without falling into a rabbit hole and unmaintainable code. There are data changes, metadata changes, undo, redo + this feature requires special kind of changes -- DDL command on the database that affects both data and metadata.
I think the only robust solution is what is implemented in this PR:
- disabled field name editing in metadata
- disabled adding new fields in metadata (needs a new feature on the data grid -- create issue)
- disabled removing new fields in metadata (needs a new feature on the data grid -- create issue)
- column renaming is implemented a separate action available in the data grid
- currently, the column …
> Rename column functionality

- client/components/Controllers/File/index.tsx
- client/components/Controllers/Table/index.tsx
- client/components/Controllers/Text/index.tsx
- client/components/Editors/Table/index.tsx
- client/store/actions/table.ts
> Fix results per page functionality

- .github/workflows/general.yaml
- electron-builder.yaml
- entitlements.mac.plist
- package.json
> 278 - MacOS Notarize

- client/components/Controllers/Table/Menu.tsx
- client/components/Parts/Bars/Menu.tsx
- client/components/Parts/Buttons/Icon.tsx
> Add error counter to menu bar errors Report Button

- client/components/Controllers/Table/Editor.tsx
- client/components/Parts/Bars/Action.tsx
- client/components/Parts/Bars/Menu.tsx
- client/components/Parts/Chips/Create.tsx
- fixes #606 
TODO : make work for Mac in a different ticket.
> Implement shortcuts

- client/components/Controllers/File/Panel.tsx
- client/components/Controllers/File/index.tsx
- client/components/Controllers/Table/Panel.tsx
- client/components/Controllers/Table/index.tsx
- client/components/Controllers/Text/Panel.tsx
- client/components/Controllers/Text/index.tsx
- client/components/Editors/Table/index.tsx
> Make panels full screen

- client/components/Controllers/Table/index.tsx
- client/components/Views/Report/Group.tsx
- client/components/Views/Report/Table.tsx
- client/components/Views/Report/assets/styles.css
> Update errors report design

- client/components/Editors/Portal/Sections/Zenodo.tsx
- client/components/Parts/Fields/Input.tsx
- client/components/Parts/Fields/Multiline.tsx
- client/components/Parts/Fields/YesNo.tsx
This PR adjusts the field widths across the app. Mostly the ones used in the Publish Dialog and the Metadata Panel.
> Fix textfield widths across the app

- client/components/Application/Dialogs/UploadFile/UploadFile.tsx
- client/components/Application/Dialogs/UploadFile/store.tsx
- server/endpoints/file/create.py
- server/endpoints/file/fetch.py
- fixes #678
- removes unused `t` argument
- adds some architectural TODOs
---
@romicolman 
This file seems to be not-properly encoded so `frictionless-py` can' read it. The only thing we can do at the moment is to improve an error message which is covered by this PR. Also, for now, it's not translated as the whole class of `frictionless-py` error messages need to be translated (it's just one case).
> Improve remote file uploading error indication

- requirements.txt
While trying to test 712-migrate-to-pyside6, running `make start` produced this error;
```python3
python -m ode.main
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/ibiam/opendataeditor/ode/main.py", line 22, in <module>
from ode.ai_widget import ChatGPTDialog
File "/home/ibiam/opendataeditor/ode/ai_widget.py", line 6, in <module>
from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai'
(/home/ibiam/opendataeditor/.python/opendataeditor/lib/python3.11/site-packages/openai/__init__.py)
make: *** [Makefile:18: start] Error 1
```
upgrading the open-ai version fixes it and the editor runs as expected.
- fixes #<issue-number>
---
Please make sure that all the checks pass. …
> Update open-ai version

- .gitignore
- ode/main.py
- ode/panels/metadata.py
- ode/paths.py
- fixes #738
This deletes the metadata as well and moves the metadata path calculation into the Paths class.
Also ignore .venv for visual studio
---
> Delete Metadata as well as file

- ode/assets/style.qss
- ode/main.py
Fixes #721
This PR implements a new ErrorsReportButton class to display an error count label next to the button.
> Add Errors number to the Errors report button in the toolbar

- ode/dialogs/upload.py
- ode/main.py
Fixes #723 
This PR ended up a little bit more challenging than expected and required a couple of small refactors. Mostly, because I needed to the path of the file uploaded out of the upload dialog to trigger actions like display views and select it in the File Navigator.
1. **DataUploadDialog:** I tried to mimic some Qt behaviour on how it handles Dialogs that returns a value. So instead of having the Dialog as an attribute I create it on the fly and return the value when the dialog is closed. We might be able to move this Dialog as a static class but I didn't want to make more complex than necessary.
2. Since our main logic (read, validate, display) is now shared by two actions (Tree click and Upload) I refactored it into it's own method `read_validate_and_display_file` that can be …
> 723 Display file after upload

- ode/panels/metadata.py
- Reorder the menu in the Metadata panel. Schema and Files going first now.
- Dialect Menu in the Metadata panel. Show it if it is a CSV otherwise, hide it.
- Some format changes done by Black
> Reorder categories in Metadata panel and show/hide menu

- ode/panels/metadata.py
@rustico this is a small fix to #773.
Changes:
- If we assign `name=''` we will get an error when reading the metadata.
- Add an empty option for Primary Key so it does not always save the first value.
```
Traceback (most recent call last):
File "/home/pdelboca/Repos/opendataeditor/ode/main.py", line 707, in update_views
self.content.metadata_widget.populate_all_forms(filepath)
File "/home/pdelboca/Repos/opendataeditor/ode/panels/metadata.py", line 458, in populate_all_forms
self.resource = self.get_or_create_metadata(filepath).get("resource")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pdelboca/Repos/opendataeditor/ode/panels/metadata.py", line 446, in get_or_create_metadata
resource = TableResource(metadata["resource"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Populate resource name only if it exists.

- ode/file.py
- ode/main.py
- ode/panels/data.py
- ode/panels/metadata.py
- ode/utils.py
Fixes #759 
This PR will implement a re reading, validation and displaying when saving the file.
Given that the file is already in memory, re-reading is not mandatory and we should be able to do only validation/displaying to be more perfomant.
I'm also reverting the `stats=True` (is not available in the stable release) to simplify some write/read logic regarding `hash` validation.
[simplescreenrecorder-2025-03-25_11.22.46.webm](https://github.com/user-attachments/assets/37367380-1234-4bb1-9478-db3bb8e4821a)
---
> 759 Re-validate file when saving

- ode/assets/style.qss
- ode/file.py
- ode/main.py
- ode/panels/data.py
- ode/panels/metadata.py
Fixes #783 
This PR:
- Disables FieldForm's name field.
- When saving the metadata, the names of the fields will always match the first row content.
- Disables the mouse scrolling of the Field's type QComboBox for a better UX when scrolling long forms.
- Adds a small validation to check if the metadata file exist before attempting to delete it to.
[simplescreenrecorder-2025-03-27_08.21.03.webm](https://github.com/user-attachments/assets/00c53c49-0fd7-45a5-a889-6482457e24f8)
> Always use the first row to set field names

- ode/panels/data.py
- ode/panels/errors.py
- tests/ode/test_application.py
- Fixes #772 
- Allows to have multiple errors in the same row
- Overrides the `data` method in the Errors report able to show for each table the error style corresponding
> Fix the Error Report panel showing the missing rows and the correct background for each error type

- ode/panels/source.py
Fixes #782 
The data viewer was working properly but I detected a small issue in the `Source` panel that was not properly reading/displaying `utf-8` encoding characters. The problem was that the current logic was not exiting as soon as it was able to read the file and re-reading it with a wrong encoding.
---
> Return content if properly read.

- .github/workflows/general.yaml
We do not need to build everything on each commit so let's not waste resources and time.
We can comment these particular lines when debugging or developing the Packaging logic.
> Run packaging only on merges and tags.

- .github/workflows/general.yaml
- fixes #884 
I'm adding two missing dependencies (`libxcb-cursor0 libxcb-shape0-dev`) to our builder to fix 2 warnings that are causing errors when running in Ubuntu and another Debian based distributions.:
```
66485 WARNING: Library not found: could not resolve 'libxcb-cursor.so.0', dependency of '/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/PySide6/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so'.
66485 WARNING: Library not found: could not resolve 'libxcb-shape.so.0', dependency of '/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/PySide6/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so'.
```
---
Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly …
> Install missing dependencies on Linux package builder

- ode/dialogs/metadata.py
- ode/panels/data.py
This makes some small fixes:
1. It resets the cursor to Arrow when clicking on the icon
2. Refactor a variable name since we are not using Dropdowns
3. Fix docstring.
---
> Small fixes on new Column's Metadata UX

- ode/assets/style.qss
Add comprehensive keyboard focus styles to the Qt Stylesheet (./ode/assets/style.qss) by appending a new section with 17 focus selectors covering all major UI components.
For more details: https://workback.ai/okfn/opendataeditor/issues/905
> fix(keyboard focus indicators): update keyboard focus styles 

- ode/main.py
- ode/panels/data.py
Fixes #904 
Some improvements:
- Our DataView is now focusable with `Tab` but navigation is only allowed with Arrow Keys. This avoid a navigation trap.
- `Enter` now expand/collapses folders in our File Navigator
- `Enter` now opens a file (like clicking on it)
- Toolbar navigation now follows logical order (passing `self` to ErrorsReportButton was overriding navigation order)
I also fixed a link for the documentation that was broken after #950 
---
> Accessibility Improvements: Keyboard navigability

- dev-requirements.txt
- ode/panels/data.py
- ode/shared.py
When working on #985 I discovered a small bug that was created by the way we were handling the changes in the cursor when the user is hovering the first row.
Current Behaviour:
- When hovering the icon we change the icon.
- When clicking on the icon we open the dialog.
- When double clicking on the cell we open the dialog. (Default Cell edit for first row is no longer available)
It makes no sense (and makes the code more dirty) to have this two behaviours so I'm proposing to:
- When hovering the cells in the first row we change the mouse pointer.
- When clicking on the cells in the first row we open the dialog.
[simplescreenrecorder-2025-08-06_11.55.53.webm](https://github.com/user-attachments/assets/75b2f01b-bf35-4dcb-a91d-dd096b1d6bf3)
> Refactor and Simplify the behavior of the first row.

- ode/panels/data.py
- requirements.txt
Saving XLS files is not working at the moment. They are being saved as XLSX, which later causes an error in Frictionless. This fixes this.
> Fix saving XLS files

- ode/assets/style.qss
- ode/file.py
- ode/main.py
- ode/panels/data.py
- Fixes #1000 
- If it’s an Excel file, a dropdown appears to switch between sheets.
- If it’s a CSV file, the dropdown is hidden.
- The user can export the current sheet with its errors.
- The user can modify and save each sheet separately.
- It doesn’t work with Google Spreadsheets, since they are saved as CSV.
> Allow the user to change between excel sheets if they exists

- ode/__init__.py
- ode/utils.py
We are receiving errors reports of the application crashing when trying to load the old json file of Open Data Editor.
This could happen by corrupted files.
```
An unexpected error occurred: JSONDecodeError: Expecting value: line 1 column 1 (char 0)" followed by
"Traceback (most recent call last):
File "ode\main.py", line 1162, in <module>
migrate_metadata_store()
~~~~~~~~~~~~~~~~~~~~~~^^
File "ode\utils.py", line 56, in migrate_metadata_store
metadata = json.load(file)
File "json\__init__.py", line 293, in load
File "json\__init__.py", line 346, in loads
File "json\decoder.py", line 345, in decode
File "json\decoder.py", line 363, in raw_decode
json.decoder.JSONDecodeError: Expectin
```
> Handle exception when migrating from v1.3

- ode/llama.py
Just a small fix. When closing the AI widget the selected prompt is not set back to the initial value.
---
> Reset prompt when closing the AI dialog.
